const os = require("os")

// Important Functions
console.log(os.hostname())
console.log(os.platform())
console.log(os.homedir())
console.log(os.userInfo())
console.log(os.arch())
console.log(os.freemem()/(1024*1024*1024))
console.log(os.totalmem()/(1024*1024*1024))
console.log(os.uptime())
console.log(os.type())
console.log(os.release())
console.log(os.cpus())
console.log(os.hostname())
console.log(os.totalmem())
console.log(os.freemem())
console.log(os.tmpdir())
console.log(os.arch())
console.log(os.networkInterfaces())